# Generated by Django 5.2.4 on 2025-07-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
